$('.links_item').click(function(){
      $('.links_item').removeClass('active');
      $('.slider_inner_img').removeClass('active');
      $(this).addClass('active');
    });
    $('.item_one').click(function(){
      $('.img_1').addClass('active');
    });
    $('.item_two').click(function(){
      $('.img_2').addClass('active');
    });
    $('.item_three').click(function(){
      $('.img_3').addClass('active');
    });
    $('.item_four').click(function(){
      $('.img_4').addClass('active');
    });
    $('.item_five').click(function(){
      $('.img_5').addClass('active');
    });